on: 
  push:
    branches: [feature-123]

jobs:

  pipeline_scan:
      runs-on: ubuntu-latest
      name: pipeline scan

      steps:
        - name: checkout
          uses: actions/checkout@v2

        - name: install node v12
          uses: actions/setup-node@v1
          with:
            node-version: 12
        
        - name: npm install
          run: npm install

        - name: pipeline-scan action step
          id: pipelien-scan
          uses: ./
          with:
            vid: ${{ secrets.VID }}
            vkey: ${{ secrets.VKEY }}
            file: "verademo.war" 
            request_policy: "VeraDemo Policy"
            store_baseline_file: true
            store_baseline_file_branch: "feature-123"
            create_baseline_from: "standard"
            debug: 1
            fail_build: true
        - name: Create comment
          uses: peter-evans/create-or-update-comment@v2
          with:
            issue-number: 4
            body: |
              This is a multi-line test comment
              - With GitHub **Markdown** :sparkles:
              - Created by [create-or-update-comment][1]

              [1]: https://github.com/peter-evans/create-or-update-comment
            reactions: '+1'