on: [push]

jobs:

  pipeline_scan:
      runs-on: ubuntu-latest
      name: pipeline scan

      steps:
        - name: checkout
          uses: actions/checkout@v2

        - name: install node v12
          uses: actions/setup-node@v1
          with:
            node-version: 12

        - name: pipeline-scan action step
          id: pipelien-scan
          uses: ./
          with:
            vid: ${{ secrets.VID }}
            vkey: ${{ secrets.VKEY }}
            file: "verademo.war" 